# Generated by Django 3.2.7 on 2021-09-18 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prisoner',
            fields=[
                ('prisoner_id', models.CharField(max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('prisoner_name', models.CharField(max_length=64, unique=True)),
                ('prisoner_image', models.FilePathField(path='/img')),
                ('prisoner_about', models.TextField()),
                ('prisoner_current_charges', models.TextField()),
                ('prisoner_old_charges', models.TextField()),
                ('prisoner_jail_time', models.PositiveSmallIntegerField()),
                ('prisoner_jail_section', models.CharField(choices=[('common', 'Nhà giam chung'), ('private', 'Nhà giam riêng'), ('diciplinary', 'Nhà kỷ luật')], default='common', max_length=20)),
                ('prisoner_jail_room', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
