# Generated by Django 3.2.7 on 2021-09-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joke_truy_na', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisoner',
            name='prisoner_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
