# Generated by Django 3.2.7 on 2021-09-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joke_truy_na', '0002_alter_prisoner_prisoner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisoner',
            name='prisoner_jail_section',
            field=models.CharField(choices=[('Nhà giam chung', 'Nhà giam chung'), ('Nhà giam riêng', 'Nhà giam riêng'), ('Nhà kỉ luật', 'Nhà kỷ luật')], default='common', max_length=20),
        ),
    ]
